# Generated by Django 4.0.4 on 2023-12-10 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(max_length=120)),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма')),
                ('operation_date_time', models.DateTimeField(auto_now_add=True)),
                ('type_of_spend', models.CharField(choices=[('SP', 'Покупки в магазинах'), ('TP', 'Проезд в общественном транспорте'), ('TI', 'Связь и интернет'), ('CR', 'Рестораны и кафе'), ('CT', 'Переводы'), ('EN', 'Развлечения'), ('FU', 'Топливо'), ('OT', 'Другие траты')], max_length=2, verbose_name='Тип операции')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(max_length=120)),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма')),
                ('operation_date_time', models.DateTimeField(auto_now_add=True)),
                ('type_of_receipt', models.CharField(choices=[('CB', 'Кэшбэк'), ('SA', 'Зарплата'), ('SC', 'Стипендия'), ('SP', 'Социальные выплаты'), ('CT', 'Переводы'), ('OT', 'Другие операции')], max_length=2, verbose_name='Тип операции')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_from', models.CharField(max_length=3)),
                ('currency_to', models.CharField(max_length=3)),
                ('amount_to_convert', models.FloatField()),
                ('converted_amount', models.FloatField()),
                ('conversion_date_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
